"""
Pipeline summary panel — renders the Summary Agent's markdown output
prominently at the top of the Results tab.
"""
from __future__ import annotations

import json
from pathlib import Path

import streamlit as st


def _extract_summary(audit_path: Path) -> str | None:
    """Walk the audit log and return the most recent summarizer output."""
    if not audit_path.exists():
        return None
    text = None
    with open(audit_path, "r", encoding="utf-8") as f:
        for line in f:
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            if e.get("kind") == "llm_call" and e["data"].get("purpose") == "summarizer":
                raw = (e["data"].get("response") or {}).get("text") or ""
                try:
                    text = json.loads(raw).get("summary") or raw
                except json.JSONDecodeError:
                    text = raw
            elif e.get("kind") == "event" and e["data"].get("name") == "summarizer.done":
                # event also stores the summary preview but full text is in llm_call
                pass
    return text


def render_summary(audit_path: Path) -> None:
    summary = _extract_summary(audit_path)
    if not summary:
        st.info("No Summary Agent output for this run (older log or mock LLM).")
        return
    with st.container(border=True):
        st.markdown("### 📋 Pipeline summary")
        st.caption("Generated by the Summary Agent from each agent's final report.")
        st.markdown(summary)
